doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options: {}
    default_database: tapandgo_%kernel.environment%
    document_managers:
        default:
            auto_mapping: true