fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: true
        formats:
            xml: false
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    body_converter:
        enabled: true
        validate: true
    routing_loader:
        default_format: json
        include_format: false
    disable_csrf_role: IS_AUTHENTICATED_ANONYMOUSLY