nelmio_api_doc:
    name:                   Tap and Go
    sandbox:
        enabled:            true
        endpoint:           null
        accept_type:        application/json
        body_format:
            formats:        null
            default_format: json
        request_format:
            formats:
                json:       application/json
                xml:        null
            method:         accept_header
            default_format: json
        authentication:
            name:           bearer
            delivery:       query
    cache:
        enabled:            false
        file:               '%kernel.cache_dir%/api-doc.cache'