<?php

namespace AppBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends DocumentRepository
{
}