<?php

namespace AppBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends DocumentRepository {

    /**
     * Get City List for the API
     * 
     * @param type $count
     * @param type $page
     * 
     * @return array
     */
    public function getCityListApi($count, $page) {

        $qb = $this->createQueryBuilder('city');

        $qb->select('id', 'name', 'coordinates');

        $qb->skip($page * $count);
        $qb->limit($count);

        $qb->hydrate(false);

        $query = $qb->getQuery();

        return $query->execute()->toArray();
    }

}
