<?php

namespace AppBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * StationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StationRepository extends DocumentRepository
{
}