<?php

namespace AppBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * StationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StationRepository extends DocumentRepository {

    /**
     * Get Station List for the API
     * 
     * @param type $limit
     * @param type $page
     * @param int $cityId
     * 
     * @return type
     */
    public function getStationListApi($limit, $page, $cityId) {

        $qb = $this->createQueryBuilder('station');

        $qb->select('id', 'creationDate', 'lastUpdate', 'name', 'address', 'description', 'coordinates', 'bikesCapacity', 'bikesAvailable');

        $qb->field('city')->equals($cityId);

        $qb->skip($page * $limit);
        $qb->limit($limit);

        $qb->hydrate(false);

        $query = $qb->getQuery();

        return $query->execute()->toArray();
    }

    /**
     * Get Station List Near for the API
     * 
     * @param float $lat
     * @param float $lng
     * @param int   $radius
     * @param int   $limit
     * 
     * @return array
     */
    public function getStationListNearApi($lat, $lng, $radius, $limit) {

        $qb = $this->createQueryBuilder('station');

        $qb->nearSphere((float) $lng, (float) $lat);
        $qb->maxDistance($radius);

        $qb->limit($limit);

        $qb->hydrate(false);

        $query = $qb->getQuery();

        return $query->execute()->toArray();
    }

}
