<?php

namespace AppBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * StationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StationRepository extends DocumentRepository {

    /**
     * Get Station List for the API
     * 
     * @param type $filters
     * @param type $orderBy
     * @param type $count
     * @param type $page
     * @return type
     */
    public function getStationListApi($filters, $orderBy, $count, $page) {

        $qb = $this->createQueryBuilder('city');

        foreach ($filters as $name => $data) {

            $filterDataName = 'filterData' . $name;
            $filterDataNameParam = ':filterData' . $name;

            $qb->andWhere($qb->expr()->like('city.' . $name, $filterDataNameParam));
            $qb->setParameter($filterDataName, '%' . $data . '%');
        }

        $qb->setFirstResult($page * $count);
        $qb->setMaxResults($count);

        return $qb->getQuery()->getArrayResult();
    }

}
